# Generated by Django 5.1.4 on 2024-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_customer", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("AadharId", models.CharField(max_length=12)),
                ("address_customer", models.CharField(max_length=200)),
            ],
        ),
    ]
