<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-30 04:10

=======
# Generated by Django 5.1.4 on 2024-12-26 10:48

import django.db.models.deletion
>>>>>>> 2e0fe1592e4fd99f15b8360054fbfc296485531e
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
<<<<<<< HEAD
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("type", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                ("contact", models.CharField(max_length=15)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hotel_images/"),
=======
                ("hotelId", models.AutoField(primary_key=True, serialize=False)),
                ("hotelName", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("hotelType", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("contact", models.CharField(max_length=100)),
                (
                    "hotel_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_No", models.IntegerField()),
                ("roomType", models.CharField(max_length=100)),
                ("price_per_room", models.FloatField(default=0.0)),
                ("available_rooms", models.IntegerField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotelapp.hotel"
                    ),
>>>>>>> 2e0fe1592e4fd99f15b8360054fbfc296485531e
                ),
            ],
        ),
    ]
