# Generated by Django 5.1.4 on 2024-12-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/hotel_images/"
            ),
        ),
    ]
