# Generated by Django 5.1.4 on 2024-12-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
