# Generated by Django 5.1.4 on 2024-12-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0004_alter_hotel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_No", models.IntegerField()),
                ("roomType", models.CharField(max_length=100)),
                ("price_per_rooms", models.FloatField(default=0.0)),
                ("available_rooms", models.IntegerField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotelapp.hotel"
                    ),
                ),
            ],
        ),
    ]
