# Generated by Django 5.1.4 on 2024-12-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0006_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="no_of_room",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
