# Generated by Django 5.1.4 on 2024-12-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0008_alter_booking_no_of_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
    ]
