# Generated by Django 5.1.4 on 2025-01-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0009_alter_booking_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingConfirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordernumber", models.CharField(max_length=100)),
                ("orderdate", models.DateTimeField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("City", models.CharField(max_length=100)),
            ],
        ),
    ]
