# Generated by Django 5.1.4 on 2025-01-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelapp", "0010_bookingconfirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingconfirm",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
