# Generated by Django 5.1.4 on 2025-01-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loginapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="email_admin",
            new_name="email",
        ),
    ]
